version: '3.8'
volumes:
  db:

services:
  api:
    build: .
    ports:
      - "7080:7080"
    volumes:
      - .:/usr/src/app
    #    command: air

    networks:
      - app-network

#  postgres:
#    image: postgres:16-bullseye
#    env_file:
#      - .env
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: sa
#      POSTGRES_DB: e-learn
#    ports:
#      - "5438:5432"
#    volumes:
#      - db:/var/lib/postgresql/data
#    #      - ./db-seed.sql:/docker-entrypoint-initdb.d/db-seed.sql
#    restart: always
#    networks:
#      app-network:
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres -d e-learn -h localhost -p 5432" ]
#      interval: 10s
#      timeout: 20s
#      retries: 5


networks:
  app-network:
    driver: bridge